service: ecommerce-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /products
          method: post
      - http:
          path: /banners
          method: post
      - http:
          path: /seo
          method: post
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      URL: https://spreadsheets.google.com/feeds/list/
      FORMAT: public/full
      EXT: ?alt=json
