service: aws-node-express-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /store
          method: get
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      URL: https://spreadsheets.google.com/feeds/list/
      FORMAT: public/full
      EXT: ?alt=json
